import "./globals.css";
import Link from 'next/link';

export const metadata = {
  title: "워크숍 레크리에이션",
  description: "Generated by LDB",
};

export default function RootLayout({ children }) {
  const now = new Date().toLocaleDateString();
  return (
    <html>
      <body>
        <div className="vertical-align">
          <div className="horizontal-align-lg inline-elements">
            <h1>{now} GI3팀 워크샵 (●'◡'●)</h1>
          </div>
          <div className="horizontal-align-lg inline-elements">
            <Link href={'/team'} className="btn btn-warning f24 marR20">팀 정하기</Link>
            <Link href={'/timer'} className="btn btn-info f24 marL20">타이머</Link>
          </div>
          <div className="horizontal-align-lg inline-elements padT0">{children}</div>
        </div>
      </body>
    </html>
  );
}
